/** 
* File Name:   ResidentesYCentros 
* Description: Classe auxiliar que contiene una tupla de residentes y centros.
* Copyright:   Konozca 
* @author:     Xavier Garcia
* Modification Log 
* =============================================================== 
*Version	Date     	Author           Modification 
* 01		05/03/2015  Xavier Garcia
* =============================================================== 
**/ 
public class ResidentesYCentros {
    public id Residente { get; set;}
   	public id Centro { get; set; }
}